# Generated by Django 5.2.9 on 2026-02-11 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('show_gender', models.BooleanField(default=True)),
                ('interested_in', models.JSONField(blank=True, default=list)),
                ('relationship_type', models.CharField(blank=True, max_length=50)),
                ('distance', models.IntegerField(default=25)),
                ('strict_distance', models.BooleanField(default=False)),
                ('drinking', models.CharField(blank=True, max_length=50)),
                ('smoking', models.CharField(blank=True, max_length=50)),
                ('workout', models.CharField(blank=True, max_length=50)),
                ('pets', models.CharField(blank=True, max_length=50)),
                ('communication_style', models.JSONField(blank=True, default=list)),
                ('response_pace', models.CharField(blank=True, max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('use_current_location', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('conversation_starter', models.CharField(blank=True, max_length=300)),
                ('social_accounts', models.JSONField(blank=True, default=dict)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('pending', 'Pending')], default='active', max_length=20)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_time', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('messages', models.IntegerField(default=0)),
                ('photo_count', models.IntegerField(default=0)),
                ('reports', models.IntegerField(default=0)),
                ('profile_complete', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
