# Generated by Django 5.2.9 on 2026-02-11 06:51

import admin_panel.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('tip', models.TextField()),
                ('icon', models.CharField(choices=[('message-circle', 'Message Circle'), ('target', 'Target'), ('sparkles', 'Sparkles'), ('lightbulb', 'Lightbulb'), ('heart', 'Heart'), ('star', 'Star'), ('zap', 'Zap'), ('users', 'Users'), ('trending-up', 'Trending Up')], default='lightbulb', max_length=20)),
                ('icon_color', models.CharField(choices=[('text-blue-500', 'Blue'), ('text-rose-500', 'Rose'), ('text-amber-500', 'Amber'), ('text-violet-500', 'Violet'), ('text-green-500', 'Green'), ('text-purple-500', 'Purple'), ('text-pink-500', 'Pink'), ('text-teal-500', 'Teal')], default='text-blue-500', max_length=20)),
                ('bg_color', models.CharField(choices=[('bg-blue-50', 'Blue'), ('bg-rose-50', 'Rose'), ('bg-amber-50', 'Amber'), ('bg-violet-50', 'Violet'), ('bg-green-50', 'Green'), ('bg-purple-50', 'Purple'), ('bg-pink-50', 'Pink'), ('bg-teal-50', 'Teal')], default='bg-blue-50', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expert Tip',
                'verbose_name_plural': 'Expert Tips',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
                'db_table': 'footer_sections',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(default='© 2026 The Dating App. All rights reserved.', max_length=200)),
                ('tagline', models.CharField(default='Made in Hyderabad, India ❤️ for genuine connections.', max_length=200)),
                ('show_copyright', models.BooleanField(default=True)),
                ('show_tagline', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
                'db_table': 'footer_settings',
            },
        ),
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('eye', 'Eye'), ('zap', 'Zap'), ('message-circle', 'Message Circle'), ('map-pin', 'Map Pin'), ('shield', 'Shield'), ('star', 'Star'), ('heart', 'Heart'), ('crown', 'Crown')], default='star', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Feature',
                'verbose_name_plural': 'Premium Features',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('plan_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', '6 Months'), ('annual', 'Annual')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_text', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(choices=[('zap', 'Zap'), ('flame', 'Flame'), ('trending-up', 'Trending Up'), ('crown', 'Crown'), ('star', 'Star')], default='zap', max_length=20)),
                ('color', models.CharField(default='from-blue-500 to-cyan-500', max_length=100)),
                ('gradient', models.CharField(default='bg-gradient-to-br from-blue-500 to-cyan-500', max_length=100)),
                ('popular', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Premium Plan',
                'verbose_name_plural': 'Premium Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('suspend', 'Suspend'), ('ban', 'Ban'), ('activate', 'Activate'), ('delete', 'Delete'), ('verify', 'Verify'), ('warn', 'Warn')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('link_type', models.CharField(choices=[('internal', 'Internal Link'), ('external', 'External Link')], default='internal', max_length=20)),
                ('open_new_tab', models.BooleanField(default=False, help_text='Open link in new tab (for external links)')),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='admin_panel.footersection')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'db_table': 'footer_links',
                'ordering': ['section', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promo code (e.g., SUMMER2024, FREEMONTH100)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description (not shown to users)')),
                ('discount_percentage', models.IntegerField(default=100, help_text='Discount percentage (100 = FREE)')),
                ('max_uses', models.IntegerField(default=100, help_text='Maximum number of people who can use this code')),
                ('current_uses', models.IntegerField(default=0, help_text='Current number of times used')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this code becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this code expires (leave empty for no expiration)', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this code is currently active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='Which plan this code applies to', on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='admin_panel.premiumplan')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.premiumplan')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='admin_panel.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'db_table': 'promo_code_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('text', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('fake', 'Fake Profile'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=admin_panel.models._default_permissions)),
                ('invite_token', models.CharField(blank=True, default=admin_panel.models._generate_invite_token, max_length=64, null=True, unique=True)),
                ('invite_accepted', models.BooleanField(default=False)),
                ('initial_password', models.CharField(blank=True, help_text='Temporary password generated on account creation', max_length=255, null=True)),
                ('password_changed', models.BooleanField(default=False, help_text='True if admin has changed their password from the initial one')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the admin was soft-deleted', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'db_table': 'admin_roles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='admin_roles_is_acti_e1f55d_idx'), models.Index(fields=['deleted_at'], name='admin_roles_deleted_15a20b_idx'), models.Index(fields=['user', 'is_active'], name='admin_roles_user_id_43b231_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promo_codes_code_5b1d05_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['active'], name='promo_codes_active_e504b4_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['user'], name='promo_code__user_id_b12e12_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodeusage',
            index=models.Index(fields=['promo_code'], name='promo_code__promo_c_469618_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('promo_code', 'user')},
        ),
    ]
